// Copyright 2026 The GoMLX Authors. SPDX-License-Identifier: Apache-2.0

package sam3

import (
	"encoding/json"
	"image"
	_ "image/png"
	"os"
	"testing"

	"github.com/gomlx/compute/dtypes"
	"github.com/gomlx/go-huggingface/hub"
	modelimage "github.com/gomlx/go-huggingface/models/image"
	_ "github.com/gomlx/gomlx/backends/default"
	. "github.com/gomlx/gomlx/core/graph"
	"github.com/gomlx/gomlx/core/tensors"
	"github.com/gomlx/gomlx/core/tensors/images"
	"github.com/gomlx/gomlx/ml/model"
	"github.com/gomlx/gomlx/support/testutil"
	"github.com/stretchr/testify/require"
)

// parityExpected mirrors test/sam3_test_data.json, which is generated by the
// reference PyTorch implementation (test/generate_test_data.py).
type parityExpected struct {
	Text                    string    `json:"text"`
	TokenIDs                []int     `json:"token_ids"`
	PixelValuesShape        []int     `json:"pixel_values_shape"`
	PixelValuesMean         float64   `json:"pixel_values_mean"`
	PixelValuesStd          float64   `json:"pixel_values_std"`
	BackboneFPNMeans        []float64 `json:"backbone_fpn_means"`
	BackboneFPNShapes       [][]int   `json:"backbone_fpn_shapes"`
	VisionPosEncMeans       []float64 `json:"vision_pos_enc_means"`
	LanguageFeaturesMean    float64   `json:"language_features_mean"`
	EncoderHiddenStatesMean float64   `json:"encoder_hidden_states_mean"`
	QueriesMean             float64   `json:"queries_mean"`
	PredLogits              []float64 `json:"pred_logits"`
	PredBoxesMean           float64   `json:"pred_boxes_mean"`
	PredMasksShape          []int     `json:"pred_masks_shape"`
	PredMasksMean           float64   `json:"pred_masks_mean"`
	PresenceLogit           []float64 `json:"presence_logit"`
	QueriesSample           []float64 `json:"queries_sample"`
	PredMasksSample         []float64 `json:"pred_masks_sample"`
}

// TestSAM3Parity compares the GoMLX implementation against reference values
// produced by the PyTorch model. The reference runs in bfloat16 (the model's
// fused MLP casts to bf16), while this implementation runs in float32, so the
// tolerances below are set for bf16-level agreement. They are tight enough to
// catch architecture, weight-mapping, and shape errors.
func TestSAM3Parity(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping SAM3 parity test in short mode")
	}

	backend := testutil.BuildTestBackend()

	// 1. Load the reference values.
	b, err := os.ReadFile("test/sam3_test_data.json")
	require.NoError(t, err)
	var expected parityExpected
	require.NoError(t, json.Unmarshal(b, &expected))

	// 2. Tokenizer parity.
	tok, err := newTokenizer("test/bpe_simple_vocab_16e6.txt.gz")
	require.NoError(t, err)
	gotTokenIDs := tok.tokenize(expected.Text)
	require.Equal(t, expected.TokenIDs, gotTokenIDs, "tokenizer mismatch")

	// 3. Load the model weights.
	repo := hub.New("dummy9996/SAM3.1-safetensors-bf16-x-fp8")
	require.NoError(t, repo.DownloadInfo(false))
	modelObj, err := LoadModel(repo)
	require.NoError(t, err)
	store := model.NewStore()
	require.NoError(t, modelObj.LoadStore(backend, store))

	// 4. Load the test image.
	imgFile, err := os.Open("test/test_image.png")
	require.NoError(t, err)
	defer imgFile.Close()
	img, _, err := image.Decode(imgFile)
	require.NoError(t, err)
	imgTensor := images.ToTensor(dtypes.Float32).Single(img)

	// 5. Build the padded (text-only) inputs.
	cfg := modelObj.Config
	points, pointLabels, pointMask := buildTestPoints(16)
	boxes, boxLabels, boxMask := buildTestBoxes(16)
	pointsTensor := tensors.FromValue(points)
	pointLabelsTensor := tensors.FromValue(pointLabels)
	pointMaskTensor := tensors.FromValue(pointMask)
	boxesTensor := tensors.FromValue(boxes)
	boxLabelsTensor := tensors.FromValue(boxLabels)
	boxMaskTensor := tensors.FromValue(boxMask)
	tokenIDs32 := make([]int32, len(gotTokenIDs))
	for i, v := range gotTokenIDs {
		tokenIDs32[i] = int32(v)
	}
	tokenTensor := tensors.FromValue([][]int32{tokenIDs32})

	// 6. Build and compile the graph, exposing intermediate means.
	exec, err := model.NewExec(backend, store, func(scope *model.Scope, inputs []*Node) []*Node {
		rawImage, tokenIDs := inputs[0], inputs[1]
		points, pointLabels, pointMask := inputs[2], inputs[3], inputs[4]
		boxes, boxLabels, boxMask := inputs[5], inputs[6], inputs[7]

		mean := []float64{0.5, 0.5, 0.5}
		std := []float64{0.5, 0.5, 0.5}
		preprocessed := modelimage.PreprocessGraph(rawImage, cfg.ImageSize, cfg.ImageSize, mean, std)
		out := Forward(scope, preprocessed, tokenIDs, points, pointLabels, pointMask, boxes, boxLabels, boxMask, cfg)

		results := []*Node{
			Squeeze(Squeeze(out.PredLogits, -1), 0), // [numQueries]
			Squeeze(out.PresenceLogit, 0),           // [1]
			ReduceMean(out.PredMasks),
			ReduceMean(out.PredBoxes),
			ReduceMean(out.EncoderMemory),
			ReduceMean(out.Queries),
			ReduceMean(out.TextMemory),
		}
		for _, f := range out.FPNFeatures {
			results = append(results, ReduceMean(f))
		}
		for _, p := range out.FPNPosEnc {
			results = append(results, ReduceMean(p))
		}
		results = append(results, Reshape(Slice(out.Queries, AxisRange(), AxisRange(0, 8), AxisRange(0, 16)), -1))
		results = append(results, Reshape(Slice(out.PredMasks, AxisRange(), AxisRange(0, 1), AxisRange(0, 1), AxisRange(0, 16)), -1))
		return results
	})
	require.NoError(t, err)

	outputs, err := exec.Call(imgTensor, tokenTensor, pointsTensor, pointLabelsTensor, pointMaskTensor, boxesTensor, boxLabelsTensor, boxMaskTensor)
	require.NoError(t, err)
	defer func() {
		for _, o := range outputs {
			o.MustFinalizeAll()
		}
	}()

	// 7. Compare.
	gotLogits := outputs[0].Value().([]float32)
	require.Len(t, gotLogits, len(expected.PredLogits))
	maxLogitDiff := float64(0)
	for i := range gotLogits {
		d := abs(float64(gotLogits[i]) - expected.PredLogits[i])
		if d > maxLogitDiff {
			maxLogitDiff = d
		}
	}

	gotPresence := outputs[1].Value().([]float32)
	gotPredMasksMean := float64(outputs[2].Value().(float32))
	gotPredBoxesMean := float64(outputs[3].Value().(float32))
	gotEncMean := float64(outputs[4].Value().(float32))
	gotQueriesMean := float64(outputs[5].Value().(float32))
	gotTextMean := float64(outputs[6].Value().(float32))
	gotFPNMeans := []float64{float64(outputs[7].Value().(float32)), float64(outputs[8].Value().(float32)), float64(outputs[9].Value().(float32))}
	gotPosEncMeans := []float64{float64(outputs[10].Value().(float32)), float64(outputs[11].Value().(float32)), float64(outputs[12].Value().(float32))}

	t.Logf("pred_logits:    max abs diff = %g (exp[0]=%g got[0]=%g)", maxLogitDiff, expected.PredLogits[0], gotLogits[0])
	t.Logf("presence_logit: expected=%v got=%v", expected.PresenceLogit, gotPresence)
	t.Logf("pred_masks_mean: exp=%g got=%g", expected.PredMasksMean, gotPredMasksMean)
	t.Logf("pred_boxes_mean: exp=%g got=%g", expected.PredBoxesMean, gotPredBoxesMean)
	t.Logf("encoder_mean:    exp=%g got=%g", expected.EncoderHiddenStatesMean, gotEncMean)
	t.Logf("queries_mean:    exp=%g got=%g", expected.QueriesMean, gotQueriesMean)
	t.Logf("text_mean:       exp=%g got=%g", expected.LanguageFeaturesMean, gotTextMean)
	for i := range 3 {
		t.Logf("backbone_fpn[%d]:   exp=%g got=%g", i, expected.BackboneFPNMeans[i], gotFPNMeans[i])
		t.Logf("vision_pos_enc[%d]: exp=%g got=%g", i, expected.VisionPosEncMeans[i], gotPosEncMeans[i])
	}
	gotQueriesSample := outputs[13].Value().([]float32)
	gotMasksSample := outputs[14].Value().([]float32)
	t.Logf("queries_sample[0:16]: exp=%v", expected.QueriesSample[:16])
	t.Logf("queries_sample[0:16]: got=%v", gotQueriesSample[:16])
	t.Logf("pred_masks_sample:     exp=%v", expected.PredMasksSample)
	t.Logf("pred_masks_sample:     got=%v", gotMasksSample)

	// bf16-level agreement.
	require.InDelta(t, expected.PredMasksMean, gotPredMasksMean, 1.0, "pred_masks mean")
	require.InDelta(t, expected.PredBoxesMean, gotPredBoxesMean, 0.05, "pred_boxes mean")
	require.InDelta(t, expected.EncoderHiddenStatesMean, gotEncMean, 0.1, "encoder memory mean")
	require.InDelta(t, expected.QueriesMean, gotQueriesMean, 0.05, "queries mean")
	require.InDelta(t, expected.LanguageFeaturesMean, gotTextMean, 0.1, "text features mean")
	for i := range 3 {
		require.InDelta(t, expected.BackboneFPNMeans[i], gotFPNMeans[i], 0.05, "backbone_fpn[%d] mean", i)
		require.InDelta(t, expected.VisionPosEncMeans[i], gotPosEncMeans[i], 0.05, "vision_pos_enc[%d] mean", i)
	}
	require.InDelta(t, expected.PredLogits[0], float64(gotLogits[0]), 0.2, "pred_logits[0]")
	require.InDelta(t, expected.PresenceLogit[0], float64(gotPresence[0]), 0.2, "presence_logit")
}

func buildTestPoints(n int) ([][][]float32, [][]int32, [][]bool) {
	pts := make([][][]float32, n)
	lbls := make([][]int32, n)
	mask := make([]bool, n)
	for i := range n {
		pts[i] = [][]float32{{0, 0}}
		lbls[i] = []int32{1}
		mask[i] = true
	}
	return pts, lbls, [][]bool{mask}
}

func buildTestBoxes(n int) ([][][]float32, [][]int32, [][]bool) {
	bxs := make([][][]float32, n)
	lbls := make([][]int32, n)
	mask := make([]bool, n)
	for i := range n {
		bxs[i] = [][]float32{{0, 0, 0, 0}}
		lbls[i] = []int32{1}
		mask[i] = true
	}
	return bxs, lbls, [][]bool{mask}
}

func abs(x float64) float64 {
	if x < 0 {
		return -x
	}
	return x
}
